// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js convention: .env.local holds real local values, .env is just the
// checked-in template. Load .env.local first so DATABASE_URL etc. resolve;
// fall back to .env for environments that use it instead (e.g. CI).
config({ path: ".env.local" });
config();

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
